# Generated by Django 4.1.4 on 2023-01-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
            preserve_default=False,
        ),
    ]
